// <auto-generated />
using System;
using EasyWashApp.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EasyWashApp.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211127030235_Primera")]
    partial class Primera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EasyWashApp.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dir_per")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad_per")
                        .HasColumnType("int");

                    b.Property<string>("Email_per")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fechanac_per")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom_per")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numdoc_per")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel1_per")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel2_per")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Persona");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("EasyWashApp.Dominio.Trabajador", b =>
                {
                    b.HasBaseType("EasyWashApp.Dominio.Persona");

                    b.Property<string>("Arl_trab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eps_trab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_trab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin_trab")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIng_trab")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pass_trab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Porcen_trab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<string>("Usu_trab")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Trabajador");
                });
#pragma warning restore 612, 618
        }
    }
}
